services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\MerconisCustomStarterbaseBundle\Display\Common\Helper\Helper:
    public: true
    autowire: false

  LeadingSystems\MerconisCustomStarterbaseBundle\Cronjob\CronDispatcher:
    arguments:
      - '@LeadingSystems\MerconisCustomStarterbaseBundle\Scheduler\SchedulerDispatcher'
    tags:
      - { name: contao.cronjob, interval: minutely, method: dispatchScheduler }

  LeadingSystems\MerconisCustomStarterbaseBundle\Scheduler\SchedulerDispatcher:
    # must only be public during development so that it can be used in apiResource_hotwireSchedulerDispatcher
    public: true
    arguments:
      - !tagged_iterator merconis_custom.schedulable

  # Schedulable services -->
  LeadingSystems\MerconisCustomStarterbaseBundle\Dummy\DummySchedulable:
    tags:
      - { name: merconis_custom.schedulable }
